parameters:
- name: environment
  default: 'dev'

stages:
- stage: ${{ parameters.environment }}_deploy

  variables:
  - group: 'fm-treasurehunt-${{ parameters.environment }}'
  - name: 'environment'
    value: ${{ parameters.environment }}

  jobs:
  - deployment: terraform_deploy

    pool:
      vmImage: 'ubuntu-latest'

    environment: 'fm-treasurehunt-${{ parameters.environment }}'

    strategy:
     runOnce:
       deploy:
        steps:
          - download: current
            displayName: 'Download terraform source artifact'
            artifact: terraform

          - task: TerraformInstaller@0
            displayName: 'Install terraform'
            inputs:
              terraformVersion: '0.12.24'

          - task: TerraformTaskV1@0
            displayName: 'Terraform: azurerm init'
            inputs:
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              backendServiceArm: 'Personal-Pay-As-You-Go'
              backendAzureRmResourceGroupName: '$(AzTerraformResourceGroup)'
              backendAzureRmStorageAccountName: '$(AzTerraformStorageAccount)'
              backendAzureRmContainerName: terraform
              backendAzureRmKey: '${{ parameters.environment }}-terraform.tfstate'

          - task: TerraformTaskV1@0
            displayName: 'Terraform : azurerm plan'
            inputs:
              command: plan
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: 'Personal-Pay-As-You-Go'

          - task: TerraformTaskV1@0
            name: terraform_validate_and_apply
            displayName: 'Terraform : azurerm validate and apply'
            inputs:
              command: apply
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: 'Personal-Pay-As-You-Go'

          - powershell: |
              $terraformOutput = Get-Content "$(terraform_validate_and_apply.jsonOutputVariablesPath)" | ConvertFrom-Json
              $terraformOutput | Get-Member -MemberType NoteProperty | % { $o = $terraformOutput.($_.Name); Write-Host "##vso[task.setvariable variable=$($_.Name);isoutput=true;issecret=$($o.sensitive)]$($o.value)" }
            name: terraform_output
            displayName: 'Read terraform output vars'

  - deployment: 'webapp_deploy'
    dependsOn: 'terraform_deploy'
    pool: 
      vmImage: 'windows-latest'

    environment: 'fm-treasurehunt-${{ parameters.environment }}'

    variables:
    - name: appdata_storage_connection
      value: $[ dependencies.terraform_deploy.outputs['terraform_deploy.terraform_output.appdata_storage_connection'] ]

    strategy:
     runOnce:
       deploy:
         steps:
          - download: current
            displayName: 'Download webapp artifact'
            artifact: webapp

          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: FM-TreasureHunt-WebApp-$(environment)'
            inputs:
              azureSubscription: 'Personal-Pay-As-You-Go'
              WebAppName: 'FM-TreasureHunt-WebApp-$(environment)'
              deployToSlotOrASE: true
              ResourceGroupName: 'FM-TH-Web-$(environment)'
              packageForLinux: '$(Pipeline.Workspace)/webapp/FM.TreasureHunt.Web.zip'
              AppSettings: '-AppDataContainer:StorageConnectionString "$(appdata_storage_connection)"'